### ISSUE TITLE
Process Not Defined(React Js)

### ISSUE THREAD

**Issue by nkinnacostly** [mpolinowski/mqtt-frontend#1]
Uncaught ReferenceError: process is not defined
at ./node_modules/mqtt/build/lib/client.js (client.ts:41:1)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:62:1)
at ./node_modules/mqtt/build/mqtt.js (mqtt.ts:8:1)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:62:1)
at ./src/components/MQTTConnector/index.js (index.js:15:1)
at options.factory (react refresh:6:1)

**Comment by mpolinowski** [comment]
Hey,

I just had a chance to try it - I am getting a lot of errors for the MQTT.js lib. Seems that there is an issue with Webpack 5:

https://github.com/mqttjs/MQTT.js/issues/1558

I followed the recommendation in the Github issue above and used the pre-compiled version `precompiled-mqtt`.  It now works for me again. I updated the repository accordingly.
